development:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: oladium
  pool: 5
  username: adelaida
  password: Jgus83igy

test:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: oladium_test
  pool: 5
  username: adelaida
  password: Jgus83igy

production:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: oladium
  pool: 5
  username: adelaida
  password: Jgus83igy
